import { TokenType } from "@/lang/token/token";

export const tokenCategories = {
  Keywords: [
    TokenType.FUNCTION,
    TokenType.LET,
    TokenType.CONST,
    TokenType.IF,
    TokenType.ELSE,
    TokenType.RETURN,
    TokenType.WHILE,
    TokenType.FOR,
    TokenType.BREAK,
    TokenType.CONTINUE,
    TokenType.ELIF,
    TokenType.CLASS,
    TokenType.EXTENDS,
    TokenType.SUPER,
    TokenType.THIS,
    TokenType.NEW,
  ],
  Literals: [
    TokenType.INT,
    TokenType.STRING,
    TokenType.TRUE,
    TokenType.FALSE,
    TokenType.NULL,
  ],
  Identifiers: [TokenType.IDENTIFIER],
  Operators: [
    TokenType.ASSIGN,
    TokenType.PLUS,
    TokenType.MINUS,
    TokenType.BANG,
    TokenType.ASTERISK,
    TokenType.SLASH,
    TokenType.MODULUS,
    TokenType.EQ,
    TokenType.NOT_EQ,
    TokenType.LESS_THAN,
    TokenType.GREATER_THAN,
    TokenType.PLUS_ASSIGN,
    TokenType.MINUS_ASSIGN,
    TokenType.ASTERISK_ASSIGN,
    TokenType.SLASH_ASSIGN,
    TokenType.AND,
    TokenType.OR,
    TokenType.BITWISE_AND,
    TokenType.BITWISE_OR,
    TokenType.BITWISE_XOR,
    TokenType.BITWISE_NOT,
    TokenType.BITWISE_LEFT_SHIFT,
    TokenType.BITWISE_RIGHT_SHIFT,
  ],
  Punctuation: [
    TokenType.COMMA,
    TokenType.SEMICOLON,
    TokenType.COLON,
    TokenType.DOT,
    TokenType.LPAREN,
    TokenType.RPAREN,
    TokenType.LBRACE,
    TokenType.RBRACE,
    TokenType.LBRACKET,
    TokenType.RBRACKET,
  ],
  Special: [TokenType.EOF, TokenType.ILLEGAL],
};
